version: '3.6'
services:
  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: